# Generated by Django 5.1.2 on 2026-05-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalnotes',
            options={'ordering': ['-created_at'], 'verbose_name': 'MedicalNotes', 'verbose_name_plural': 'MedicalNotes'},
        ),
    ]
