# Generated by Django 5.1.2 on 2026-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicalrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='hospital_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
